# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-alpha-dust
telegram_url: https://telegram.org/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: liuqitao.mail@foxmail.com
rss_url: \#

# Footer About Text
footer_about: "
This is my notebook. You can think of it as a post it note. The following is the shortcut hexo original subject address by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>.  My<a href=\"https://github.com/light-come\">Light</a>My light come and contact information. QQ group 546256946"

# Footer Copyright Line
footer_copyright: "<p>Copyright © 2021 <a href=\"#\"> taoistcore.com </a> All Rights Reserved  ICP<a style=\"cursor: pointer;\" onclick=\"window.open(`https://beian.miit.gov.cn`) \">皖ICP备18010834号</a> | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a></p>"

